### ISSUE TITLE
Multiple Server instances

### ISSUE THREAD

**Issue by jylups** [thmhoag/arkserver#13]
## Image Setup Details

* **Image Tag**: latest

* **Docker Host OS**: Linux Ubuntu

* **`docker run` command or `docker-compose.yml` file**: 
    ```
   version: '3.3'
services:
    arkserver:
        volumes:
            - /var/data/arkcrystalisles/steam:/home/steam/Steam
            - /var/data/arkcrystalisles/ark:/ark
            - /var/data/clusters:/ark/server/ShooterGame/Saved/clusters
        ports:
            - 27017:27017
            - 27017:27017/udp
            - 7788:7788
            - 7788:7788/udp
            - 7789:7789
            - 7789:7789/udp
            - 7790:7790
            - 7790:7790/udp
        container_name: arkcrystalisles
        environment:
            - am_ark_QueryPort=27017
            - am_ark_SessionName=6/20 [Cyrstal Isles] 20x All [MetalHeads]
            - am_ark_Port=7789
            - am_serverMap=CrystalIsles
        image: thmhoag/arkserver
    ```

## Description of Issue

Description of issue
Getting a time out when running multiple instances of the docker image. Opened all the ports in firewall. Redirected previous and next port from ark_Port. Does anybody have this problem? Is this an ark server problem or a configuration? Default Values worked for port 7777 and 7778 and query port 27015 but no new instances can be used on the same host
