### ISSUE TITLE
Timeout when connecting, doesn't use specified gameport

### ISSUE THREAD

**Issue by fredrikscode** [thmhoag/arkserver#15]
* **Image Tag**: latest
* **Docker Host OS**:  Ubuntu 18.04.4 LTS
* **`docker run` command or `docker-compose.yml` file**: 
    ```
    version: "3"
  services:
  ragnarok:
    container_name: ragnarok
    image: thmhoag/arkserver:latest
    volumes:
      - /home/ark/maps/ragnarok:/ark
      - /home/ark/clusterdata:/ark/clusterdata
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27015:27015/udp
      - 27030:27030/tcp
    ```

## Description of Issue
The server goes up as expected but for some reason clients get timeout when connecting. 

## Additional Information
There's currently no software or hardware firewall on the host. No errors when not running detached. Displays port 7776 in server browser (only thing I can think of that would change the port automatically is rawsockets and it increases the port, doesn't decrease it). Ended up setting ports in both arkmanager.cfg and the instance.cfg, no luck. 

Container displays these ports: 0.0.0.0:7777-7778->7777-7778/udp, 0.0.0.0:27015->27015/udp, 0.0.0.0:27030->27030/tcp
