### ISSUE TITLE
Server config

### ISSUE THREAD

**Issue by Tychus** [thmhoag/arkserver#2]
While trying to configure the server, changing different values https://ark.gamepedia.com/Server_Configuration#Configuration_Files  after launching the server the values are never loaded correctly seems like the server falls back to some sort of default settings file. Are we missing something here ? where should we put our custom config file

**Comment by thmhoag** [comment]
Hey @Tychus, could you be more specific on where you are putting your config files?

The image is setup so that the config can be mounted to the `/ark/config` directory and it will be symlinked to the correct directory in the server path, but in theory I don't believe there would be anything preventing you from mounting it directly to the `/ark/server/ShooterGame/Saved/Config/LinuxServer` path, I've just never tested it that way.

**Comment by Tychus** [comment]
Thanks for answering.
We wrote the first file in `/ark/config` didn't work, we saved it after that in `/ark/server/ShooterGame/Saved/Config/LinuxServer` which also didn't work. 

Found some `DefaultXXXX.ini` files around not sure if that's what ends up being the used i'll try changing stuff their see if it works. Did you load modified multipliers before ? if yes can you tell us how to do it ?

**Comment by thmhoag** [comment]
Yes, loading the configs should work. Could you post an example of the `docker run` command you're using, or the `docker-compose.yml` if you're using that?

I don't typically use the `DefaultXXX.ini` files as they can get overwritten when the game updates. 

Here's an example of a `docker-compose.yml` file from my test server:
```
version: '3'

volumes:
  steam:
  ark:
  ark-saved:
  ark-backups:
  ark-testcluster:

services:
  ark_test:
    image: thmhoag/arkserver:1.3.0
    container_name: ark_test
    hostname: ark_test
    ports:
      - 7786:7786/udp
      - 7786:7786
      - 7787:7787/udp
      - 7787:7787
      - 27023:27023/udp
      - 27023:27023
      - 32338:32338
    environment:
      - am_ark_Port=7787
      - am_ark_QueryPort=27023
      - am_ark_RCONEnabled=True
      - am_ark_RCONPort=32338
      - am_ark_MaxPlayers=70
      - am_ark_SessionName=TestServer
      - am_serverMap=Valguero_P
      - am_ark_ServerAdminPassword=testme
      - am_arkwarnminutes=15
      - am_ark_GameModIds=1999447172,812655342,1135049053,1675932178,1404697612
      - am_ark_arkMaxBackupSizeGB=1
      - am_ark_AltSaveDirectoryName=valguero
      - am_arkflag_NoTransferFromFiltering=
      - am_arkopt_clusterid=cluster-test
      - am_ark_OverrideOfficialDifficulty=5
      - am_ark_AllowAnyoneBabyImprintCuddle=true
      - am_ark_AllowFlyingStaminaRecovery=true
      - am_ark_bAllowPlatformSaddleMultiFloors=true
      - am_ark_OverrideStructurePlatformPrevention=true
      - TZ=UTC
    volumes:
      - steam:/home/steam/.steam/SteamApps/workshop
      - ark:/ark
      - ark-saved:/ark/server/ShooterGame/Saved/valguero
      - ark-backups:/ark/backup
      - ark-testcluster:/ark/server/ShooterGame/Saved/clusters
      - ./GameUserSettings.ini:/ark/config/GameUserSettings.ini
      - ./Game.ini:/ark/config/Game.ini
    restart: always
```

For this compose file above, the `Game.ini` and `GameUserSettings.ini` files are stored and mounted from the same directory as the `docker-compose.yml`.
