### ISSUE TITLE
Example Docker-compose ideally with cluster configuration

### ISSUE THREAD

**Issue by Gamewalker** [thmhoag/arkserver#28]
Hello,

I hope its ok to ask here, I dont have an issue.
Anyone out there who has a working docker-compose file for a cluster configuration build on this repo?

Thanks

edit:
managed to write this one:
```version: "3.7"

volumes:
  steam:

services:
    scorched:
        image: thmhoag/arkserver
        container_name: ark_scorched
        hostname: scorched
        volumes:
            # LOKAL -> CONTAINER
            - '/media/storage/gameserver/ark/steam:/home/steam/Steam'
            - '/media/storage/gameserver/ark/ark:/ark'
        ports:
            - '27015:27015'
            - '27015:27015/udp'
            - '7777:7777'
            - '7777:7777/udp'
            - '7778:7778'
            - '7778:7778/udp'
            - '32338:32338'
        environment:
            - am_ark_QueryPort=27015
            - am_ark_Port=7777
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32338
            - am_ark_SessionName=C4E.dev Scorched Earth
            - am_serverMap=ScorchedEarth_P
            - am_ark_AltSaveDirectoryName=ScorchedEarth
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107,2121156303
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_PreventDownloadSurvivors="False"
            - am_ark_PreventDownloadItems="False"
            - am_ark_PreventDownloadDinos="False"
            - am_ark_PreventUploadSurvivors="False"
            - am_ark_PreventUploadItems="False"
            - am_ark_PreventUploadDinos="False"
        restart: unless-stopped
    ragnarok:
        image: thmhoag/arkserver
        container_name: ark_ragnarok
        hostname: ragnarok
        volumes:
            # LOKAL -> CONTAINER
            - '/media/storage/gameserver/ark/steam:/home/steam/Steam'
            - '/media/storage/gameserver/ark/ark:/ark'
        ports:
            - '27016:27016'
            - '27016:27016/udp'
            - '7779:7779'
            - '7779:7779/udp'
            - '7780:7780'
            - '7780:7780/udp'
            - '32339:32339'
        environment:
            - am_ark_QueryPort=27016
            - am_ark_Port=7780
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32339
            - am_ark_SessionName=C4E.dev Ragnarok
            - am_serverMap=Ragnarok
            - am_ark_AltSaveDirectoryName=Ragnarok
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107,2121156303
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_PreventDownloadSurvivors="False"
            - am_ark_PreventDownloadItems="False"
            - am_ark_PreventDownloadDinos="False"
            - am_ark_PreventUploadSurvivors="False"
            - am_ark_PreventUploadItems="False"
            - am_ark_PreventUploadDinos="False"
        restart: unless-stopped
    aberration:
        image: thmhoag/arkserver
        container_name: ark_aberration
        hostname: aberration
        volumes:
            # LOKAL -> CONTAINER
            - '/media/storage/gameserver/ark/steam:/home/steam/Steam'
            - '/media/storage/gameserver/ark/ark:/ark'
        ports:
            - '27017:27017'
            - '27017:27017/udp'
            - '7781:7781'
            - '7781:7781/udp'
            - '7782:7782'
            - '7782:7782/udp'
            - '32340:32340'
        environment:
            - am_ark_QueryPort=27017
            - am_ark_Port=7781
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32340
            - am_ark_SessionName=C4E.dev Aberration
            - am_serverMap=Aberration_P
            - am_ark_AltSaveDirectoryName=Aberration
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107,2121156303
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_PreventDownloadSurvivors="False"
            - am_ark_PreventDownloadItems="False"
            - am_ark_PreventDownloadDinos="False"
            - am_ark_PreventUploadSurvivors="False"
            - am_ark_PreventUploadItems="False"
            - am_ark_PreventUploadDinos="False"
        restart: unless-stopped
    extinction:
        image: thmhoag/arkserver
        container_name: ark_extinction
        hostname: extinction
        volumes:
            # LOKAL -> CONTAINER
            - '/media/storage/gameserver/ark/steam:/home/steam/Steam'
            - '/media/storage/gameserver/ark/ark:/ark'
        ports:
            - '27018:27018'
            - '27018:27018/udp'
            - '7783:7783'
            - '7783:7783/udp'
            - '7784:7784'
            - '7784:7784/udp'
            - '32341:32341'
        environment:
            - am_ark_QueryPort=27018
            - am_ark_Port=7783
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32341
            - am_ark_SessionName=C4E.dev Extinction
            - am_serverMap=Extinction
            - am_ark_AltSaveDirectoryName=Extinction
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107,2121156303
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_PreventDownloadSurvivors="False"
            - am_ark_PreventDownloadItems="False"
            - am_ark_PreventDownloadDinos="False"
            - am_ark_PreventUploadSurvivors="False"
            - am_ark_PreventUploadItems="False"
            - am_ark_PreventUploadDinos="False"
        restart: unless-stopped
    genesis:
        image: thmhoag/arkserver
        container_name: ark_genesis
        hostname: genesis
        volumes:
            # LOKAL -> CONTAINER
            - '/media/storage/gameserver/ark/steam:/home/steam/Steam'
            - '/media/storage/gameserver/ark/ark:/ark'
        ports:
            - '27019:27019'
            - '27019:27019/udp'
            - '7785:7785'
            - '7785:7785/udp'
            - '7786:7786'
            - '7786:7786/udp'
            - '32342:32342'
        environment:
            - am_ark_QueryPort=27019
            - am_ark_Port=7785
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32342
            - am_ark_SessionName=C4E.dev Genesis
            - am_serverMap=Genesis
            - am_ark_AltSaveDirectoryName=Genesis
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107,2121156303
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_PreventDownloadSurvivors="False"
            - am_ark_PreventDownloadItems="False"
            - am_ark_PreventDownloadDinos="False"
            - am_ark_PreventUploadSurvivors="False"
            - am_ark_PreventUploadItems="False"
            - am_ark_PreventUploadDinos="False"
        restart: unless-stopped
```

but docker compose up -d isnt working because the instances share PID/lock files, what am I missing? docker-compose up -d scorched is working fine (single instance)

edit2:
Its working with this config but different dir for every instance ...

```
version: "3.7"

volumes:
  steam:

services:
    scorched:
        image: thmhoag/arkserver
        container_name: ark_scorched
        hostname: scorched
        volumes:
            # LOKAL -> CONTAINER
            - '/ark/scorched_steam:/home/steam/Steam'
            - '/ark/scorched_arkmanager:/ark'
            - '/ark/cluster:/cluster'
            - '/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - '/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27015:27015/udp'
            - '7777:7777/udp'
            - '7778:7778/udp'
            - '32338:32338'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27015
            - am_ark_Port=7778
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32338
            - am_ark_SessionName=C4E.dev Scorched Earth
            - am_serverMap=ScorchedEarth_P
            - am_ark_AltSaveDirectoryName=ScorchedEarth
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="c4e"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    ragnarok:
        image: thmhoag/arkserver
        container_name: ark_ragnarok
        hostname: ragnarok
        volumes:
            # LOKAL -> CONTAINER
            - '/ark/ragnarok_steam:/home/steam/Steam'
            - '/ark/ragnarok_arkmanager:/ark'
            - '/ark/cluster:/cluster'
            - '/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - '/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27016:27016/udp'
            - '7779:7779/udp'
            - '7780:7780/udp'
            - '32339:32339'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27016
            - am_ark_Port=7780
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32339
            - am_ark_SessionName=C4E.dev Ragnarok
            - am_serverMap=Ragnarok
            - am_ark_AltSaveDirectoryName=Ragnarok
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="c4e"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    aberration:
        image: thmhoag/arkserver
        container_name: ark_aberration
        hostname: aberration
        volumes:
            # LOKAL -> CONTAINER
            - '/ark/aberration_steam:/home/steam/Steam'
            - '/ark/aberration_arkmanager:/ark'
            - '/ark/cluster:/cluster'
            - '/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - '/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27017:27017/udp'
            - '7781:7781/udp'
            - '7782:7782/udp'
            - '32340:32340'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27017
            - am_ark_Port=7782
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32340
            - am_ark_SessionName=C4E.dev Aberration
            - am_serverMap=Aberration_P
            - am_ark_AltSaveDirectoryName=Aberration
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="c4e"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    extinction:
        image: thmhoag/arkserver
        container_name: ark_extinction
        hostname: extinction
        volumes:
            # LOKAL -> CONTAINER
            - '/ark/extinction_steam:/home/steam/Steam'
            - '/ark/extinction_arkmanager:/ark'
            - '/ark/cluster:/cluster'
            - '/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - '/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27018:27018/udp'
            - '7783:7783/udp'
            - '7784:7784/udp'
            - '32341:32341'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27018
            - am_ark_Port=7784
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32341
            - am_ark_SessionName=C4E.dev Extinction
            - am_serverMap=Extinction
            - am_ark_AltSaveDirectoryName=Extinction
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="c4e"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    genesis:
        image: thmhoag/arkserver
        container_name: ark_genesis
        hostname: genesis
        volumes:
            # LOKAL -> CONTAINER
            - '/ark/genesis_steam:/home/steam/Steam'
            - '/ark/genesis_arkmanager:/ark'
            - '/ark/cluster:/cluster'
            - '/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - '/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27019:27019/udp'
            - '7785:7785/udp'
            - '7786:7786/udp'
            - '32342:32342'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27019
            - am_ark_Port=7786
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32342
            - am_ark_SessionName=C4E.dev Genesis
            - am_serverMap=Genesis
            - am_ark_AltSaveDirectoryName=Genesis
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="c4e"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
```
