### ISSUE TITLE
 mkdir: cannot create directory '/ark/log': Permission denied

### ISSUE THREAD

**Issue by mattiasghodsian** [thmhoag/arkserver#42]
Am trying to set up a cluster server but when i spin it up i get **Permission denied** on **/ark/log**, any idea to solve this?

docker-compose -up 
```bash
Creating network "ark_cluster_default" with the default driver
Creating ark_theisland ... done
Creating ark_scorched  ... done
Attaching to ark_scorched, ark_theisland
ark_scorched | ###########################################################################
ark_theisland | ###########################################################################
ark_theisland | # Ark Server -  Thu Jun 24 08:07:48 UTC 2021
ark_theisland | ###########################################################################
ark_theisland | Ensuring correct permissions...
ark_scorched | # Ark Server -  Thu Jun 24 08:07:48 UTC 2021
ark_scorched | ###########################################################################
ark_scorched | Ensuring correct permissions...
ark_scorched | Cleaning up any leftover arkmanager files...
ark_scorched | mkdir: cannot create directory '/ark/log': Permission denied
ark_theisland | Cleaning up any leftover arkmanager files...
ark_theisland | mkdir: cannot create directory '/ark/log': Permission denied
```
```bash
.
├── config
│   ├── cluster
│   ├── Game.ini
│   ├── GameUserSettings.ini
│   ├── scorched_arkmanager
│   │   └── config
│   │       ├── Game.ini
│   │       └── GameUserSettings.ini
│   ├── scorched_steam
│   ├── theisland_arkmanager
│   │   └── config
│   │       ├── Game.ini
│   │       └── GameUserSettings.ini
│   └── theisland_steam
├── docker-compose.yml
├── docker-compose.yml-bk
├── scorched.env
└── theisland.env
```

docker-compose.yml
```yml
version: "3.7"

volumes:
  steam:

services:
    theisland:
        image: thmhoag/arkserver
        container_name: ark_theisland
        hostname: theisland
        volumes:
            - './config/theisland_steam:/home/steam/Steam'
            - './config/theisland_arkmanager:/ark'
            - './config/cluster:/cluster'
            - './config/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - './config/Game.ini:/ark/config/Game.ini'
        ports:
            - '27015:27015/udp'
            - '7777:7777/udp'
            - '7778:7778/udp'
            - '32342:32342'
        env_file:
            - theisland.env
        restart: unless-stopped
    scorched:
        image: thmhoag/arkserver
        container_name: ark_scorched
        hostname: scorched
        volumes:
            - './config/scorched_steam:/home/steam/Steam'
            - './config/scorched_arkmanager:/ark'
            - './config/cluster:/cluster'
            - './config/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - './config/Game.ini:/ark/config/Game.ini'
        ports:
            - '27016:27016/udp'
            - '7785:7785/udp'
            - '7786:7786/udp'
            - '32338:32338'
        env_file:
            - scorched.env
        restart: unless-stopped
```

theisland.env
```env
LC_ALL=C
am_ark_QueryPort=27015
am_ark_Port=7778
am_ark_ShowFloatingDamageText=True
am_ark_RCONEnabled=True
am_ark_RCONPort=32342
am_ark_SessionName=C4E.dev The Island
am_serverMap=TheIsland
am_ark_AltSaveDirectoryName=TheIsland
am_ark_MaxPlayers=20
am_arkwarnminutes=0
#am_ark_GameModIds=
am_arkflag_NoTransferFromFiltering=""
am_ark_ServerPassword=asd
am_ark_ServerAdminPassword=asd
arkopt_activeevent=TurkeyTrial
am_arkopt_clusterid="c4e"
am_arkopt_ClusterDirOverride="/cluster"
```

scorched.env
```env
LC_ALL=C
am_ark_QueryPort=27016
am_ark_Port=7778
am_ark_ShowFloatingDamageText=True
am_ark_RCONEnabled=True
am_ark_RCONPort=32338
am_ark_SessionName=C4E.dev Scorched Earth
am_serverMap=ScorchedEarth_P
am_ark_AltSaveDirectoryName=ScorchedEarth
am_ark_MaxPlayers=20
am_arkwarnminutes=0
#am_ark_GameModIds=
am_arkflag_NoTransferFromFiltering=""
am_ark_ServerPassword=asd
am_ark_ServerAdminPassword=asdf
arkopt_activeevent=TurkeyTrial
am_arkopt_clusterid="c4e"
am_arkopt_ClusterDirOverride="/cluster"
```
