### ISSUE TITLE
Cluster setup - invalid mode

### ISSUE THREAD

**Issue by mattiasghodsian** [thmhoag/arkserver#47]
AM trying to setup a cluster server on my Ubuntu machine and keep getting **invalid mode:** 

Root folder
```
➜  arkserver tree
.
├── data
├── docker-compose.yml
└── docker-compose.yml.old

1 directory, 2 files
```

log
```
arkserver docker-compose up -d 
Creating network "arkserver_default" with the default driver
Creating ark_extinction ... 
Creating ark_aberration ... 
Creating ark_extinction ... error
Creating ark_scorched   ... 
Creating ark_ragnarok   ... 
Creating ark_aberration ... error
ERROR: for ark_genesis  Cannot create container for service genesis: invalid mode: /ark

ERROR: for ark_extinction  Cannot create container for service extinction: invalid mode: /ark

Creating ark_ragnarok   ... error
Creating ark_scorched   ... error
ERROR: for ark_ragnarok  Cannot create container for service ragnarok: invalid mode: /cluster

ERROR: for ark_scorched  Cannot create container for service scorched: invalid mode: /home/steam/Steam

ERROR: for genesis  Cannot create container for service genesis: invalid mode: /ark

ERROR: for extinction  Cannot create container for service extinction: invalid mode: /ark

ERROR: for aberration  Cannot create container for service aberration: invalid mode: /home/steam/Steam

ERROR: for ragnarok  Cannot create container for service ragnarok: invalid mode: /cluster

ERROR: for scorched  Cannot create container for service scorched: invalid mode: /home/steam/Steam
ERROR: Encountered errors while bringing up the project.
```
docker-compose.yml
```
version: "3.7"

volumes:
  steam:

services:
    scorched:
        image: thmhoag/arkserver
        container_name: ark_scorched
        hostname: scorched
        volumes:
            - './data/ark/scorched_steam:/home/steam/Steam'
            - './data/ark/scorched_arkmanager:/ark'
            - './data/ark/cluster:/cluster'
            - './data/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - './data/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27015:27015/udp'
            - '7777:7777/udp'
            - '7778:7778/udp'
            - '32338:32338'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27015
            - am_ark_Port=7778
            # - am_ark_ServerPassword=test
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32338
            - am_ark_ServerAdminPassword=wdv365365
            - am_ark_SessionName=Test - Scorched Earth
            - am_serverMap=ScorchedEarth_P
            - am_ark_AltSaveDirectoryName=ScorchedEarth
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            # - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="lf"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    ragnarok:
        image: thmhoag/arkserver
        container_name: ark_ragnarok
        hostname: ragnarok
        volumes:
            - './data/ark/ragnarok_steam:/home/steam/Steam'
            - './data/ark/ragnarok_arkmanager:/ark'
            - './data/ark/cluster:/cluster'
            - './data/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - './data/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27016:27016/udp'
            - '7779:7779/udp'
            - '7780:7780/udp'
            - '32339:32339'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27016
            - am_ark_Port=7780
            # - am_ark_ServerPassword=test
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32339
            - am_ark_ServerAdminPassword=wdv365365
            - am_ark_SessionName=Test - Ragnarok
            - am_serverMap=Ragnarok
            - am_ark_AltSaveDirectoryName=Ragnarok
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            # - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="lf"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    aberration:
        image: thmhoag/arkserver
        container_name: ark_aberration
        hostname: aberration
        volumes:
            - './data/ark/aberration_steam:/home/steam/Steam'
            - './data/ark/aberration_arkmanager:/ark'
            - './data/ark/cluster:/cluster'
            - './data/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - './data/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27017:27017/udp'
            - '7781:7781/udp'
            - '7782:7782/udp'
            - '32340:32340'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27017
            - am_ark_Port=7782
            # - am_ark_ServerPassword=test
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32340
            - am_ark_ServerAdminPassword=wdv365365
            - am_ark_SessionName=Test - Aberration
            - am_serverMap=Aberration_P
            - am_ark_AltSaveDirectoryName=Aberration
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            # - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="lf"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    extinction:
        image: thmhoag/arkserver
        container_name: ark_extinction
        hostname: extinction
        volumes:
            - './data/ark/extinction_steam:/home/steam/Steam'
            - './data/ark/extinction_arkmanager:/ark'
            - './data/ark/cluster:/cluster'
            - './data/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - './data/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27018:27018/udp'
            - '7783:7783/udp'
            - '7784:7784/udp'
            - '32341:32341'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27018
            - am_ark_Port=7784
            # - am_ark_ServerPassword=test
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32341
            - am_ark_ServerAdminPassword=wdv365365
            - am_ark_SessionName=Test - Extinction
            - am_serverMap=Extinction
            - am_ark_AltSaveDirectoryName=Extinction
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            # - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="lf"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
    genesis:
        image: thmhoag/arkserver
        container_name: ark_genesis
        hostname: genesis
        volumes:
            - './data/ark/genesis_steam:/home/steam/Steam'
            - './data/ark/genesis_arkmanager:/ark'
            - './data/ark/cluster:/cluster'
            - './data/ark/GameUserSettings.ini:/ark/config/GameUserSettings.ini'
            - './data/ark/Game.ini:/ark/config/Game.ini'
        ports:
            - '27019:27019/udp'
            - '7785:7785/udp'
            - '7786:7786/udp'
            - '32342:32342'
        environment:
            - LC_ALL=C
            - am_ark_QueryPort=27019
            - am_ark_Port=7786
            # - am_ark_ServerPassword=test
            - am_ark_ShowFloatingDamageText=True
            - am_ark_RCONEnabled=True
            - am_ark_RCONPort=32342
            - am_ark_ServerAdminPassword=wdv365365
            - am_ark_SessionName=Test - Genesis
            - am_serverMap=Genesis
            - am_ark_AltSaveDirectoryName=Genesis
            - am_ark_MaxPlayers=10
            - am_arkwarnminutes=0
            # - am_ark_GameModIds=2185399633,2140170832,2227091285,893834064,1404697612,731604991,791674340,670764308,2278341478,2247979980,1251632107
            - am_arkflag_NoTransferFromFiltering=""
            - am_ark_ServerPassword=asdf
            - am_ark_ServerAdminPassword=asdf
            - arkopt_activeevent=TurkeyTrial
            - am_arkopt_clusterid="lf"
            - am_arkopt_ClusterDirOverride="/cluster"
        restart: unless-stopped
```
