### ISSUE TITLE
Mod was not successfully downloaded

### ISSUE THREAD

**Issue by nordcomputer** [thmhoag/arkserver#6]
## Image Setup Details

* **Image Tag**: v1.4.1

* **Docker Host OS**: Debian 10

* **`docker run` command or `docker-compose.yml` file**: 
  

```
version: '3'

volumes:
  steam:
  ark:
  ark-saved:
  ark-backups:
  ark-testcluster:

services:
  ark_test:
    image: thmhoag/arkserver:latest
    container_name: arkserver
    hostname: arkserver
    ports:
      - 7786:7786/udp
      - 7786:7786
      - 7787:7787/udp
      - 7787:7787
      - 27023:27023/udp
      - 27023:27023
      - 32338:32338
    environment:
      - am_ark_Port=7787
      - am_ark_QueryPort=27023
      - am_ark_RCONEnabled=True
      - am_ark_RCONPort=32338
      - am_ark_MaxPlayers=70
      - am_ark_SessionName=OdElmServer
      - am_serverMap=TheIsland
      - am_ark_ServerPassword=testing
      - am_ark_ServerAdminPassword=testingtesting
      - am_arkwarnminutes=15
      - am_ark_GameModIds=538827119
      - am_ark_arkMaxBackupSizeGB=1
      - am_ark_AltSaveDirectoryName=island
      - am_arkflag_NoTransferFromFiltering=
      - am_arkopt_clusterid=cluster-test
      - am_ark_OverrideOfficialDifficulty=5
      - am_ark_AllowAnyoneBabyImprintCuddle=true
      - am_ark_AllowFlyingStaminaRecovery=true
      - am_ark_bAllowPlatformSaddleMultiFloors=true
      - am_ark_OverrideStructurePlatformPrevention=true
      - TZ=UTC
      - am_EnablePvPGamma=true
      - am_XPMultiplier=3.000000
      - am_TamingSpeedMultiplier=3.000000
      - am_HarvestAmountMultiplier=3.000000
      - am_steamcmdroot="/usr/games"                                 # path of your steamcmd instance
      - am_steamcmdexec="steamcmd"                                             # name of steamcmd executable
      - am_steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
      - am_steamcmd_appinfocache="/home/steam/.steam/appcache/appinfo.vdf"      # cache of the appinfo command
      - am_steamcmd_workshoplog="/home/steam/.steam/logs/workshop_log.txt"      # Steam workshop log
    volumes:
      - steam:/home/steam/.steam/SteamApps/workshop
      - ./ark:/ark
      - ark-saved:/ark/server/ShooterGame/Saved/
      - ark-backups:/ark/backup
      - ark-testcluster:/ark/server/ShooterGame/Saved/clusters
      - ./GameUserSettings.ini:/ark/config/GameUserSettings.ini
      - ./Game.ini:/ark/config/Game.ini
    restart: always
```

## Description of Issue

Having hard times to get mods working - I tried to change the steamcmd part and the steamcmdroot in the compose file, but nothing seems to work. I still get
```
Mod 538827119 download failed
Mod 538827119 was not successfully downloaded
```

## Additional Information

seems like something is going wrong with the directory of steamcmd I guess?

**Comment by thmhoag** [comment]
Hey @nordcomputer, this looks like a bug with the image to me. When mounting a volume to the workshop directory, docker is setting the owner of that directory to `root` which causes `steamcmd` to fail to write to the directory.

I have committed a fix for this (pr #7) and cut a new release, you should be able to pull the new tag, `thmhoag/arkmanager:1.4.2`, and test again to make sure it resolves your issue.

Just a couple other things I noticed when testing your docker-compose.yml - 
* It looks like the /ark path was meant to be mounted to a named volume, but it's mounted to a relative volume. You may want to consider changing the `./ark:/ark` mount to be `ark:/ark` to take advantage of the named volume you created in the `volumes:` section at the top.
* You shouldn't need any of the variables listed after `am_HarvestAmountMultiplier`. They are all defined correctly in the `/etc/arkmanager/arkmanager.cfg` file in the image. Specifically, I'd recommend removing these environment variables from your `docker-compose.yml`:
  * `am_steamcmdroot`
  * `am_steamcmdexec`
  * `am_steamcmd_user`
  * `am_steamcmd_appinfocache`
  * `am_steamcmd_workshoplog`

Please be sure to test again using `thmhoag/arkserver:1.4.2` and let me know if this resolves your issue.

**Comment by nordcomputer** [comment]
Hey, thank you for the bugfix - Seems like its not possible to install mods - unfortunately the server itself isnt working for me.
I deleted the unnecessary entries. The ./ark was intended, as I need to restore a backup later.
Still, the server exits with `An update is currently in progress. Start aborted`

My edited docker-compose.yml:

```
version: '3'

volumes:
  steam:

services:
  ark:
    image: thmhoag/arkserver:latest
    container_name: arkserver
    hostname: arkserver
    ports:
      - 7786:7786/udp
      - 7786:7786
      - 7787:7787/udp
      - 7787:7787
      - 27023:27023/udp
      - 27023:27023
      - 32338:32338
    environment:
      - am_ark_Port=7787
      - am_ark_QueryPort=27023
      - am_ark_RCONEnabled=True
      - am_ark_RCONPort=32338
      - am_ark_MaxPlayers=70
      - am_ark_SessionName=OdElmServer
      - am_serverMap=TheIsland
      - am_ark_ServerPassword=Testing
      - am_ark_ServerAdminPassword=TestingTesting
      - am_arkwarnminutes=15
      - am_ark_GameModIds=731604991,655261420,566885854,761535755,554678442,510590313,566887000,693416678,538827119

      - am_ark_arkMaxBackupSizeGB=1
      - am_ark_AltSaveDirectoryName=island
      - am_arkflag_NoTransferFromFiltering=
      - am_arkopt_clusterid=cluster-test
      - am_ark_OverrideOfficialDifficulty=5
      - am_ark_AllowAnyoneBabyImprintCuddle=true
      - am_ark_AllowFlyingStaminaRecovery=true
      - am_ark_bAllowPlatformSaddleMultiFloors=true
      - am_ark_OverrideStructurePlatformPrevention=true
      - TZ=UTC
      - am_EnablePvPGamma=true
      - am_XPMultiplier=3.000000
      - am_TamingSpeedMultiplier=3.000000
      - am_HarvestAmountMultiplier=3.000000
    volumes:
      - steam:/home/steam/.steam/SteamApps/workshop
      - ./ark:/ark
      # - ./GameUserSettings.ini:/ark/config/GameUserSettings.ini //not sure about those - will they be created, if not existend?
      # - ./Game.ini:/ark/config/Game.ini //not sure about those - will they be created, if not existend?
    restart: always


```
Is this file running at your system? 
FYI: I tested with GameUserSettings.ini/Game.ini and without (as in the code above)
